# - name: Logstash 
#   hosts: localhost
#   become: yes
#   roles:
#   - role: /home/ubuntu/logstash-role/logstash-tool

---
- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - logstash-tool